site_name: The Jackal Programming Language

theme:
  name: material
  features:
    - navigation.top
    - search.highlight
    - search.suggest
    - toc.follow
    - toc.integrate
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: teal
      accent: deep orange
      toggle:
        icon: material/weather-night
        name: Switch to light mode

nav:
  - index.md
  - Jackal:
      - jackal/index.md
  - Sahara:
      - sahara/index.md
      - sahara/memory-execution-model.md
      - sahara/global-context.md
      - sahara/execution-context.md
      - sahara/data-layout.md
      - sahara/value.md
      - sahara/modules.md
      - sahara/functions.md
      - sahara/data-types.md
      - sahara/traits.md
      - sahara/conditions.md
      - sahara/effects.md
      - sahara/static-memory.md
      - sahara/dynamic-memory.md
      - sahara/bytecode.md
      - sahara/debug.md
      - sahara/metaprogramming.md

extra:
  consent:
    title: Cookie consent
    description: |
      This site uses cookies to recognize your repeated visits and preferences, and
      to measure the effectiveness of our documentation. Opting in to cookies helps us
      continue to improve our documentation.
    actions: [accept, reject, manage]
    cookies:
      analytics:
        name: Google Analytics
        checked: true
      github:
        name: GitHub
        checked: true
