[package]
name = "sahara"
version = "0.1.0"
edition = "2021"

[lib]
name = "sahara"
path = "src/lib.rs"

[[bin]]
name = "sahara-vm"
path = "bin/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
